config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'comments/index'

  get 'comments/new'

  get 'sessions/new', to: "sessions#new"
  delete 'sessions/destroy' => 'sessions#destroy'

  
  resources :sessions, only:[:new, :create]
  resources :registrations, only: [:new,:create]
  resources :users
  resources :courses
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :books do
    resources :comments
  end

  resources :logs do
    resources :comments 
  end

   root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :readers
  has_many :logs
  has_many :users, through: :readers
  has_many :comments, as: :commentable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    # binding.pry
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to new_log_path }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { redirect_to new_log_path }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:authors, :title, :link)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class="container">
  <div class="col-sm-11">
    <div class="row">
      <div class="col-sm-6">
        <div class="well bs-component">
          <div class="form-horizontal">
            <fieldset>
              <% if params[:action] == "edit" %>
                <legend>Edit Book</legend>
              <%else%>
                <legend>Add a Book</legend>
              <% end %>
                <%= form_for @book, :html => {:id => "add-book-form"} do |f| %>
                  <div class="form-group">
                    <%= f.label :title, 'Title', class: "col-sm-2 control-label"%>
                      <div class="col-sm-10">
                        <%= f.text_field :title, class: "form-control"%>
                      </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :authors, 'Author', class: "col-sm-2 control-label"%>
                      <div class="col-sm-10">
                        <%= f.text_field :authors, class: "form-control"%>
                      </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :link, 'Link', class: "col-sm-2 control-label"%>
                      <div class="col-sm-10">
                        <%= f.text_field :link, class: "form-control"%>
                      </div>
                  </div>
            </fieldset>
          </div>
        </div>
      </div>
    </div>
  </div>
 <div class="col-sm-11">
  <div class="row">
    <div class="col-sm-2">
      <%= f.submit "Submit", class:"btn btn-primary" %>
        <% end %>
    </div>
  </div>
 </div>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="container">
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Readers</th>
        <th>Link</th>
      </tr>
    </thead>
    <tbody>
     <% @books.find_each do |book| %>
      <tr>
        <td><%=book.title%></td>
        <td><%=book.authors%></td>
        <td><%=book.readers.count%></td>
        <td><%= link_to("See it on Amazon", "#{book.link}")%></td>
      </tr>
     <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>