config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'comments/index'

  get 'comments/new'

  get 'sessions/new', to: "sessions#new"
  delete 'sessions/destroy' => 'sessions#destroy'

  
  resources :sessions, only:[:new, :create]
  resources :registrations, only: [:new,:create]
  resources :users
  resources :courses
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :books do
    resources :comments
  end

  resources :logs do
    resources :comments 
  end

   root 'welcome#index'

end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  has_many :comments, as: :commentable
  validates :book_id, presence: true
  validates :content, presence: true
  validates :pages, presence: true
  validates :minutes, presence: true
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
    @comment = Comment.new
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
    @book = Book.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    # binding.pry
    @log = Log.new(log_params)
    @reader = Reader.first_or_create(book_id: @log.book_id, user_id: @log.user_id)
    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:content, :book_id, :pages, :minutes, :user_id)
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<br>
<br>
<div class="container">
 <div class="well bs-component">
  <div class="form-horizontal">
   <fieldset>
   <% if params[:action] == "edit" %>
    <legend>Edit Reading Log</legend>
   <%else%>
    <legend>Create a Reading Log Entry</legend>
   <% end %>
     <%= form_for @log do |f| %>
      <div class="form-group">
       <%= f.label :book_id, 'Select a Book', class: "col-lg-2 control-label"%>
        <div class="col-sm-6">
         <!-- <div class="row"> -->
         <%= f.collection_select :book_id, Book.all, :id, :title, {}, {class: "form-control"} %>
         </div>
        <div class="col-sm-2">
         <a href="#" class="btn btn-info form-inline" id="bookModal">Add a Book</a>
         </div>
        <!--  </div> -->
        </div>

      <div class="form-group">
       <%= f.label :pages, 'Pages Read', class: "col-lg-2 control-label"%>
        <div class="col-lg-1">
         <%= f.text_field :pages, class: "form-control"%>
        </div>
      </div>
      <div class="form-group">
       <%= f.label :minutes, 'Minutes Read', class: "col-lg-2 control-label"%>
        <div class="col-lg-1">
         <%= f.text_field :minutes, class: "form-control"%>
       </div>
      </div>
     <div class="form-group">
       <%= f.label :content, 'Talk about what you read. Did you like/dislike this part of the book? What do you think will happen next?', class: "col-lg-2 control-label"%>
        <div class="col-lg-10">
         <%= f.text_area :content, :size => "60%x5%", class: "form-control"%>
       </div>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id%>
    </fieldset>
   </div>
  </div>
    <%= f.submit "Submit", class:"btn btn-primary" %>
    <% end %>
</div>

<div class="modal" id="addBook">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <!-- <h4 class="modal-title">Add a Book</h4> -->
      </div>
      <div class="modal-body">
     <!--   <div class="container col-lg-5">
        <div class="row"> -->
         <%= render 'books/form' %>
        </div>
       </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>

app/views/logs/_log.html.erb
  <ul class="timeline">
  <% if log.id.even? %>
    <li>
  <% else %>
    <li class="timeline-inverted">
  <% end %>
      <div class="timeline-badge"><i class="glyphicon glyphicon-user"></i></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title"><%= log.book.title %></h4>
          <p><small class="text-muted"><i class="glyphicon glyphicon-book"></i> <%= log.pages %> pages</small>    <small class="text-muted"><i class="fa fa-hourglass-start"></i> <%= log.minutes %> minutes</small><small class="text-muted pull-right"><i class="glyphicon glyphicon-time"></i> <%= log.created_at.strftime("%B %-d, %Y") %></small></p>
        </div>
        <div class="timeline-body well">
          <p><%= log.content %></p>
        </div>
          <div class="timeline-body">
          <div class="">
           <ul class="list-group log-comments-<%=log.id%>">
           <% log.comments.last(5).each do |comment| %>
             <li class="list-group-item li-comment-<%=comment.id%>">
             <%if comment.user_id == current_user.id %>
               <span class="badge"><%= link_to("/logs/#{log.id}/comments/#{comment.id}", method: :delete, remote: true) do %>
                  <i class="glyphicon glyphicon-trash"></i> 
                <% end %> 
               </span>
             <% end %>
               <%= comment.words %>
             </li> 
             <% end %>
            </ul>
          </div>
          </div>
        <span class="btn btn-primary btn-xs comment-btn" id="comment-btn-<%=log.id%>">Comment</span>
        <div class="form-group comments-form comments-form-<%=log.id%>">
         <%= form_tag("/logs/#{log.id}/comments", method: "post", remote: true) do %>
          <%= text_field_tag "words", "", class: "form-control"%>
          <%= hidden_field_tag "commentable_type", "Log"%>
          <%= hidden_field_tag "commentable_id", "#{log.id}" %>
          <%= hidden_field_tag "user_id", "#{current_user.id}" %>
          <%= submit_tag "Submit", class:"btn btn-primary btn-sm submit-comment" %> 
         <% end %>
    </div>
   </div>
  </li>
</ul>

app/views/logs/edit.html.erb
<%= render 'form' %>

app/views/logs/index.html.erb
<div class="container">
  <div class="page-header">
    <h1 id="timeline">Timeline</h1>
  </div>
<%= render @logs %>
</div>

app/views/logs/new.html.erb
<%= render 'form' %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>